language: csharp

sudo: required
dist: trusty
env:
  - CLI_VERSION=latest

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8

mono:
  - latest

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"

before_script:
  - openssl aes-256-cbc -K $encrypted_e86a7a1dbeca_key -iv $encrypted_e86a7a1dbeca_iv -in .travisdeploykey.enc -out .travisdeploykey -d
  - chmod go-rwx .travisdeploykey
  - eval `ssh-agent -s`
  - ssh-add .travisdeploykey
  - git config --global user.name "Travis-CI"
  - git config --global user.email "noreply@travis-ci.org"
    
script:
  - set -e
  - scripts/detect_changes.sh
  - if [ -d tmp/gh-pages ]; then git -C tmp/gh-pages push origin gh-pages; fi
